name: Bug Report 🐛
description: 创建 Bug 报告以帮助我们改进 / Create a report to help us improve
title: 🐛[BUG]
assignees: 
  - misaka10843
labels: bug
body:
  - type: textarea
    attributes:
      label: 🐛 描述(Description)
      description: >-
        详细地描述 bug，让大家都能理解/Describe the bug in detail so that everyone can
        understand it
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📷 复现步骤(Steps to Reproduce)
      description: >-
        清晰描述复现步骤，让别人也能看到问题/Clearly describe the reproduction steps so that
        others can see the problem
      value: |-
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ' 📄 [异常/日志]信息([Exception/Log] Information)'
      description: 如报错等其他信息可以贴在这里/Other information such as crash can be posted here
      render: Shell
  - type: markdown
    attributes:
      value: '## 🚑 **基本信息(Basic Information)**'
  - type: input
    attributes:
      label: 版本(version)
      description: >-
        请填写当前程序的版本号、哈希号 / Please enter the version number/hash number of the
        current program
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 系统(OS)
      description: 在哪些系统中出现此问题/In which systems does this problem occur
      multiple: true
      options:
        - Windows10~+
        - Windows7~-
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 是否确认在单独环境下也有此问题？
      description: 在无其他mod的环境下测试是否有相关问题
      options:
        - label: 我非常确认在单独环境下也有此问题
          required: true
  - type: checkboxes
    attributes:
      label: 是否确认在降级之后问题消失？
      description: 在使用了之前的版本之后问题消失？
      options:
        - label: 我非常确认在降级之后问题消失
  - type: textarea
    attributes:
      label: 📄 配置文件(Configuration file)
  - type: textarea
    attributes:
      label: ' 🖼 截图(Screenshots)'
      description: 截图可以贴在这里/Screenshots can be posted here
